# Analyzing World Economy and Regions

Tasks:
- Perform World level economic analysis
- Perform Region level economic analysis
- Explore wbgapi for fetching real-time data
- Update Resume
- Apply 50 places

In [1]:
import pandas as pd
import os
import numpy as np
import matplotlib.pyplot as plt
import altair as alt

## Read the Data

In [2]:
DATAPATH='../assets'

In [3]:
FILENAME='WEO_Data-groups.xlsx'
df_groups=pd.read_excel(os.path.join(DATAPATH,FILENAME),engine='openpyxl')
print(df_groups.shape)
df_groups.head()

(1666, 57)

,WEO Country Group Code,Country Group Name,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,1981,1982,...,2020,2021,2022,2023,2024,2025,2026,2027,2028,Estimates Start After
0,1,World,"Gross domestic product, constant prices",NaN,Percent change,NaN,NaN,2.151,2.052,0.694,...,-2.803,6.337,3.482,2.964,2.941,3.198,3.203,3.141,3.066,NaN
1,1,World,"Gross domestic product, constant prices",NaN,Percent change (market exchange rates),NaN,NaN,1.697,2.073,0.486,...,-3.208,6.129,3.038,2.532,2.414,2.699,2.721,2.646,2.570,NaN
2,1,World,"Gross domestic product, current prices",NaN,U.S. dollars,Billions,NaN,11232.069,11526.241,11310.303,...,84960.903,96487.666,100135.361,104476.432,109734.270,115598.839,121580.994,127499.667,133782.888,NaN
3,1,World,"Gross domestic product, current prices",NaN,Purchasing power parity; international dollars,Billions,NaN,13401.939,14988.046,15971.455,...,133451.759,148174.764,163837.197,174789.867,183947.224,193602.077,203624.971,213802.005,224380.471,NaN
4,1,World,"Gross domestic product, deflator",NaN,"Index, 2000=100",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
FOLDERPATH='aligned'
FILENAME='WEO_Oct2023_country_region.xlsx'
df_imf=pd.read_excel(os.path.join(DATAPATH,FOLDERPATH,FILENAME),engine='openpyxl')
print(df_imf.shape)
df_imf.head()

(8624, 60)

,Unnamed: 0,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,...,2020,2021,2022,2023,2024,2025,2026,2027,2028,Estimates Start After
0,0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,...,1288.87,1021.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
1,1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,NaN,"See notes for: Gross domestic product, consta...",...,-2.351,-20.737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
2,2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,...,1547.29,1232.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
3,3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",...,20.136,14.941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
4,4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",...,81.007,67.093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0

In [12]:
df_imf['Country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bhutan', 'Bolivia, Plurinational State of',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo, The Democratic Republic of the', 'Congo',
       'Costa Rica', "CÃ´te d'Ivoire", 'Croatia', 'Cyprus', 'Czechia',
       'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador',
       'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
       'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
       'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran, Islamic Republic of', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'South Korea', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia, Federated States of', 'Moldova, Republic of',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway',
       'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Romania', 'Russian Federation', 'Rwanda',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia',
       'South Africa', 'South Sudan', 'Spain', 'Sri Lanka',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Taiwan, Province of China',
       'Tajikistan', 'Tanzania, United Republic of', 'Thailand',
       'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'TÃ¼rkiye', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela, Bolivarian Republic of', 'Viet Nam',
       'West Bank and Gaza', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [5]:
df_groups=df_groups.rename({'Country Group Name':'Country'},axis=1)
df_groups.head()

,WEO Country Group Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,1981,1982,...,2020,2021,2022,2023,2024,2025,2026,2027,2028,Estimates Start After
0,1,World,"Gross domestic product, constant prices",NaN,Percent change,NaN,NaN,2.151,2.052,0.694,...,-2.803,6.337,3.482,2.964,2.941,3.198,3.203,3.141,3.066,NaN
1,1,World,"Gross domestic product, constant prices",NaN,Percent change (market exchange rates),NaN,NaN,1.697,2.073,0.486,...,-3.208,6.129,3.038,2.532,2.414,2.699,2.721,2.646,2.570,NaN
2,1,World,"Gross domestic product, current prices",NaN,U.S. dollars,Billions,NaN,11232.069,11526.241,11310.303,...,84960.903,96487.666,100135.361,104476.432,109734.270,115598.839,121580.994,127499.667,133782.888,NaN
3,1,World,"Gross domestic product, current prices",NaN,Purchasing power parity; international dollars,Billions,NaN,13401.939,14988.046,15971.455,...,133451.759,148174.764,163837.197,174789.867,183947.224,193602.077,203624.971,213802.005,224380.471,NaN
4,1,World,"Gross domestic product, deflator",NaN,"Index, 2000=100",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_groups['Subject Descriptor'].nunique()

116

In [7]:
df_groups['Subject Descriptor'].unique()

array(['Gross domestic product, constant prices',
       'Gross domestic product, current prices',
       'Gross domestic product, deflator',
       'Gross domestic product per capita, constant prices',
       'Gross domestic product per capita, current prices', 'Output gap',
       'Gross domestic product based on purchasing-power-parity (PPP) share of world total',
       'Investment', 'Gross national savings',
       'Inflation, average consumer prices',
       'Inflation, end of period consumer prices',
       'Trade volume of goods and services',
       'Volume of imports of goods and services',
       'Volume of imports of goods',
       'Volume of exports of goods and services',
       'Volume of exports of goods',
       'Terms of trade of goods and services', 'Terms of trade of goods',
       'Export price of manufactures', 'Unemployment rate', 'Employment',
       'General government revenue',
       'General government total expenditure',
       'General government net lending/borrowing',
       'General government structural balance',
       'General government primary net lending/borrowing',
       'General government net debt', 'General government gross debt',
       'Current account balance', 'Imports of goods and services',
       'Exports of goods and services', 'Financial account balance',
       'Direct investment, net', 'Portfolio investment, net',
       'Financial derivatives, net', 'Other investment, net',
       'Change in reserves', 'External debt, total',
       'External debt, total debt service',
       'External debt, total debt service, interest',
       'External debt, total debt service, amortization',
       'Commodity Price Index includes both Fuel and Non-Fuel Price Indices',
       'Commodity Non-Fuel Price Index includes Food and Beverages and Industrial Inputs Price Indices',
       'Commodity Industrial Inputs Price Index includes Agricultural Raw Materials and Metals Price Indices',
       'Crude Oil (petroleum), simple average of three spot prices; Dated Brent, West Texas Intermediate, and the Dubai Fateh, US$ per barrel',
       'Crude Oil (petroleum),  Dated Brent, light blend 38 API, fob U.K., US$ per barrel',
       'Oil; Dubai, medium, Fateh 32 API, fob Dubai Crude Oil (petroleum), Dubai Fateh Fateh 32 API, US$ per barrel',
       'Crude Oil (petroleum), West Texas Intermediate 40 API, Midland Texas, US$ per barrel',
       'Commodity Fuel (energy) Index includes Crude oil (petroleum), Natural Gas, and Coal Price Indices',
       'Crude Oil (petroleum), Price index simple average of three spot prices (APSP); Dated Brent, West Texas Intermediate, and the Dubai Fateh',
       'Commodity Natural Gas Price Index includes European, Japanese, and American Natural Gas Price Indices',
       'Natural Gas, Russian Natural Gas border price in Germany, US$ per million metric British thermal units of gas',
       'Natural Gas, Indonesian Liquified Natural Gas in Japan, US$ per million metric British thermal units of liquid',
       'Natural Gas, Natural Gas spot price at the Henry Hub terminal in Louisiana, US$ per million metric British thermal units of gas',
       'Commodity Coal Price Index includes Australian and South African Coal',
       'Coal, Australian thermal coal, 1200- btu/pound, less than 1% sulfur, 14% ash, FOB Newcastle/Port Kembla, US$ per metric tonne',
       'Coal, South African export price, US$ per metric tonne',
       'Commodity Food and Beverage Price Index includes Food and Beverage Price Indices',
       'Commodity Food Price Index includes Cereal, Vegetable Oils, Meat, Seafood, Sugar, Bananas, and Oranges Price Indices',
       'Commodity Cereals Price Index includes Wheat, Maize (Corn), Rice, and Barley',
       'Wheat, No.1 Hard Red Winter, ordinary protein, FOB Gulf of Mexico, US$ per metric tonne',
       'Maize (corn), U.S. No.2 Yellow, FOB Gulf of Mexico, U.S. price, US$ per metric tonne',
       'Rice, 5 percent broken milled white rice, Thailand nominal price quote, US$ per metric tonne',
       'Barley, Canadian no.1 Western Barley, spot price, US$ per metric tonne',
       'Commodity Vegetable Oil Index includes Soybean, Soybean Meal, Soybean Oil, Rapeseed Oil, Palm Oil, Sunflower Oil, Olive Oil, Fishmeal, and Groundnut Price Indices',
       'Soybeans, U.S. soybeans, Chicago Soybean futures contract (first contract forward) No. 2 yellow and par, US$ per metric tonne',
       'Soybean Meal, Chicago Soybean Meal Futures (first contract forward) Minimum 48 percent protein, US$ per metric tonne',
       'Soybean Oil, Chicago Soybean Oil Futures (first contract forward) exchange approved grades, US$ per metric tonne',
       'Rapeseed oil, crude, FOB Rotterdam, US$ per metric ton',
       'Palm oil, Malaysia Palm Oil Futures (first contract forward) 4-5 percent FFA, US$ per metric tonne',
       'Sunflower Oil, US export price from Gulf of Mexico, US$ per metric tonne',
       'Olive Oil, extra virgin less than 1% free fatty acid, ex-tanker price U.K., US$ per metric tonne',
       'Fishmeal, Peru Fish meal/pellets 65% protein, CIF, US$ per metric tonne',
       'Groundnuts (peanuts), 40/50 (40 to 50 count per ounce), cif Argentina, US$ per metric tonne',
       'Commodity Meat Price Index includes Beef, Lamb, Swine (pork), and Poultry Price Indices',
       'Beef, Australian and New Zealand 85% lean fores, FOB U.S. import price, US cents per pound',
       'Lamb, frozen carcass Smithfield London, US cents per pound',
       'Swine (pork), 51-52% lean Hogs, U.S. price, US cents per pound',
       'Poultry (chicken), Whole bird spot price, Georgia docks, US cents per pound',
       'Commodity Seafood Index includes Fish (salmon) and Shrimp Price Indices',
       'Fish (salmon), Farm Bred Norwegian Salmon, export price, US$ per kilogram',
       'Shrimp, Frozen shell-on headless, block 16/20 count, Indian origin, C&F Japan, US$ per kilogram',
       'Commodity Sugar Index includes European, Free market, and U.S. Price Indices',
       'Sugar, Free Market, Coffee Sugar and Cocoa Exchange (CSCE) contract no.11 nearest future position, US cents per pound',
       'Sugar, U.S. import price, contract no.14 nearest futures position, US cents per pound',
       'Bananas, Central American and Ecuador, FOB U.S. Ports, US$ per metric tonne',
       'Oranges, miscellaneous oranges French import price, US$ per metric tonne',
       'Commodity Beverage Price Index includes Coffee, Tea, and Cocoa',
       'Commodity Coffee Price Index includes Other Mild Arabicas and Robusta',
       'Coffee, Other Mild Arabicas, International Coffee Organization New York cash price, ex-dock New York, US cents per pound',
       'Coffee, Robusta, International Coffee Organization New York cash price, ex-dock New York, US cents per pound',
       'Cocoa beans, International Cocoa Organization cash price, CIF US and European ports, US$ per metric tonne',
       'Tea, Mombasa, Kenya, Auction Price, US cents per kilogram',
       'Commodity Agricultural Raw Materials Index includes Timber, Cotton, Wool, Rubber, and Hides Price Indices',
       'Commodity Timber Index includes Hardwood and Softwood Price Indices',
       'Commodity Hardwood Price Index includes Hardwood Logs and Hardwood Sawn Price Indices',
       'Hard Logs, Best quality Malaysian meranti, import price Japan, US$ per cubic meter',
       'Hard Sawnwood, Dark Red Meranti, select and better quality, C&F U.K port, US$ per cubic meter',
       'Commodity Softwood Index includes Softwood Sawn and Softwood Logs Price Indices',
       'Soft Logs, Average Export price from the U.S. for Douglas Fir, US$ per cubic meter',
       'Soft Sawnwood, average export price of Douglas Fir, U.S. Price, US$ per cubic meter',
       'Cotton, Cotton Outlook `A Index`, Middling 1-3/32 inch staple, CIF Liverpool, US cents per pound',
       'Commodity Wool Index includes Coarse and Fine Wool Price Indices',
       'Wool, fine, 19 micron, Australian Wool Exchange spot quote, US cents per kilogram',
       'Wool, coarse, 23 micron, Australian Wool Exchange spot quote, US cents per kilogram',
       'Rubber, No.1 Rubber Smoked Sheet, FOB Maylaysian/Singapore, US cents per pound',
       'Hides, Heavy native steers, over 53 pounds, wholesale dealer`s price, US cents per pound',
       'Commodity Metals Price Index includes Copper, Aluminum, Iron Ore, Tin, Nickel, Zinc, Lead, and Uranium Price Indices',
       'Copper, grade A cathode, LME spot price, CIF European ports, US$ per metric tonne',
       'Aluminum, 99.5% minimum purity, LME spot price, CIF UK ports, US$ per metric tonne',
       'Iron Ore, China import Iron Ore Fines 62% FE spot (CFR Tianjin port) US$ per metric ton',
       'Tin, standard grade, LME spot price, US$ per metric tonne',
       'Nickel, melting grade, LME spot price, CIF European ports, US$ per metric tonne',
       'Zinc, high grade 98% pure, US$ per metric tonne',
       'Lead, 99.97% pure, LME spot price, CIF European Ports, US$ per metric tonne',
       'Uranium, u3o8 restricted price, Nuexco exchange spot, US$ per pound',
       nan], dtype=object)

In [8]:
range_start=1980
range_end=2008
years=np.arange(range_start,range_end+1)
years

array([1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008])

In [9]:
subjects_to_keep=['Gross domestic product, constant prices',
       'Gross domestic product, current prices',
       'Gross domestic product, deflator',
       'Gross domestic product per capita, constant prices',
       'Gross domestic product per capita, current prices', 'Output gap',
       'Gross domestic product based on purchasing-power-parity (PPP) share of world total',
       'Investment', 'Gross national savings',
       'Inflation, average consumer prices',
       'Inflation, end of period consumer prices',
       'Trade volume of goods and services',
       'Volume of imports of goods and services',
       'Volume of imports of goods',
       'Volume of exports of goods and services',
       'Volume of exports of goods',
       'Terms of trade of goods and services', 'Terms of trade of goods',
       'Export price of manufactures', 'Unemployment rate', 'Employment',
       'General government revenue',
       'General government total expenditure',
       'General government net lending/borrowing',
       'General government structural balance',
       'General government primary net lending/borrowing',
       'General government net debt', 'General government gross debt',
       'Current account balance', 'Imports of goods and services',
       'Exports of goods and services', 'Financial account balance',
       'Direct investment, net', 'Portfolio investment, net',
       'Financial derivatives, net', 'Other investment, net',
       'Change in reserves', 'External debt, total',
       'External debt, total debt service',
       'External debt, total debt service, interest',
       'External debt, total debt service, amortization']
len(subjects_to_keep)

41

In [10]:
df_grps=df_groups[df_groups['Subject Descriptor'].isin(subjects_to_keep)]
df_grps.shape

(689, 57)

In [11]:
df_groups['Country'].unique()

array(['World', 'Advanced economies', 'Euro area',
       'Major advanced economies (G7)',
       'Other advanced economies (Advanced economies excluding G7 and euro area)',
       'European Union', 'ASEAN-5',
       'Emerging market and developing economies',
       'Emerging and developing Asia', 'Emerging and developing Europe',
       'Latin America and the Caribbean', 'Middle East and Central Asia',
       'Sub-Saharan Africa', nan], dtype=object)

In [85]:
df_world=df_grps[df_grps['Country']=='World']
df_world.shape

(53, 57)

In [86]:
df_world.head(10)

,WEO Country Group Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,1980,1981,1982,...,2020,2021,2022,2023,2024,2025,2026,2027,2028,Estimates Start After
0,1,World,"Gross domestic product, constant prices",NaN,Percent change,NaN,NaN,2.151,2.052,0.694,...,-2.803,6.337,3.482,2.964,2.941,3.198,3.203,3.141,3.066,NaN
1,1,World,"Gross domestic product, constant prices",NaN,Percent change (market exchange rates),NaN,NaN,1.697,2.073,0.486,...,-3.208,6.129,3.038,2.532,2.414,2.699,2.721,2.646,2.570,NaN
2,1,World,"Gross domestic product, current prices",NaN,U.S. dollars,Billions,NaN,11232.069,11526.241,11310.303,...,84960.903,96487.666,100135.361,104476.432,109734.270,115598.839,121580.994,127499.667,133782.888,NaN
3,1,World,"Gross domestic product, current prices",NaN,Purchasing power parity; international dollars,Billions,NaN,13401.939,14988.046,15971.455,...,133451.759,148174.764,163837.197,174789.867,183947.224,193602.077,203624.971,213802.005,224380.471,NaN
4,1,World,"Gross domestic product, deflator",NaN,"Index, 2000=100",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,World,"Gross domestic product per capita, constant pr...",NaN,Purchasing power parity; 2017 international do...,Units,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,World,"Gross domestic product per capita, current prices",NaN,Purchasing power parity; international dollars,Units,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,World,Output gap,NaN,Percent of potential GDP,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,World,Gross domestic product based on purchasing-pow...,These data form the basis for the country weig...,Percent,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,World,Investment,NaN,Percent of GDP,NaN,NaN,26.500,25.896,24.436,...,26.359,27.071,27.351,26.361,26.189,26.275,26.431,26.528,26.626,NaN

In [87]:
def get_series(df,regions,subject,units,years):
    df_tmp=df[(df['Country'].isin(regions)) & (df['Subject Descriptor']==subject) & (df['Units']==units)]
    cols_to_keep=['Country']+ years
    df_tmp=df_tmp[cols_to_keep]
    df_tmp=df_tmp.rename({'Country':''},axis=1)
    df_tmp=df_tmp.set_index('')
    df_tmp=df_tmp.T.reset_index()
    df_tmp=df_tmp.rename({'index':'Year'},axis=1)
    return df_tmp

In [88]:
regions=['World']
subject='Gross domestic product, current prices'
units='U.S. dollars'
years=np.arange(1980,2028).tolist()
df_tmp=get_series(df_world,regions,subject,units,years)
# df_tmp=df_world[(df_world['Country Group Name'].isin(country)) & (df_world['Subject Descriptor']==subject) & (df_world['Units']==units)]
# estimate_year=int(df_tmp.loc[df_tmp.index[0],'Estimates Start After'])
df_tmp.tail()

    Year       World
43  2023  104476.432
44  2024  109734.270
45  2025  115598.839
46  2026  121580.994
47  2027  127499.667

In [89]:
alt.Chart(df_tmp).mark_line(point=True).encode(
    alt.X('Year').title('Year'),
    alt.Y('World').title(subject+' ('+units+')'),
    tooltip=['Year', 'World']
).interactive()

alt.Chart(...)

In [46]:
cols_to_keep=['Subject Descriptor','Units']+ years
df_tmp=df_world[cols_to_keep]
# df_tmp=df_tmp.rename({'Country Group Name':''},axis=1)
df_tmp=df_tmp.set_index('Subject Descriptor')
df_tmp=df_tmp.T.reset_index()
df_tmp=df_tmp.rename({'index':'Year'},axis=1)
df_tmp

Subject Descriptor,Year,"Gross domestic product, constant prices","Gross domestic product, constant prices","Gross domestic product, current prices","Gross domestic product, current prices","Gross domestic product, deflator","Gross domestic product per capita, constant prices","Gross domestic product per capita, current prices",Output gap,Gross domestic product based on purchasing-power-parity (PPP) share of world total,...,"External debt, total","External debt, total debt service","External debt, total debt service","External debt, total debt service","External debt, total debt service, interest","External debt, total debt service, interest","External debt, total debt service, interest","External debt, total debt service, amortization","External debt, total debt service, amortization","External debt, total debt service, amortization"
0,Units,Percent change,Percent change (market exchange rates),U.S. dollars,Purchasing power parity; international dollars,"Index, 2000=100",Purchasing power parity; 2017 international do...,Purchasing power parity; international dollars,Percent of potential GDP,Percent,...,Percent of exports of goods and services,U.S. dollars,Percent of GDP,Percent of exports of goods and services,U.S. dollars,Percent of GDP,Percent of exports of goods and services,U.S. dollars,Percent of GDP,Percent of exports of goods and services
1,1980,2.151,1.697,11232.069,13401.939,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1981,2.052,2.073,11526.241,14988.046,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1982,0.694,0.486,11310.303,15971.455,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1983,2.597,2.742,11610.283,16989.664,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1984,4.567,4.811,12025.117,18378.285,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1985,3.631,3.662,12553.732,19635.674,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1986,3.588,3.344,14793.158,20717.483,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1987,3.872,3.752,17032.786,22033.006,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1988,4.652,4.555,19156.083,23839.268,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1989,3.778,3.788,20154.504,25678.433,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1990,3.428,3.141,22643.041,27712.123,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1991,2.659,1.937,23667.7,29345.326,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1992,2.314,2.522,25351.636,33336.876,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1993,2.032,1.682,26075.732,34787.413,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1994,3.218,3.384,28026.544,36573.058,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1995,3.339,2.901,31243.753,38700.118,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1996,3.911,3.313,32113.067,40917.974,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1997,4.009,3.491,32029.533,43306.054,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1998,2.611,2.357,31881.27,45003.405,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1999,3.546,3.161,33008.737,47206.85,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2000,4.814,4.243,34103.065,50593.437,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,2001,2.47,1.682,33857.249,52984.92,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2002,2.873,1.871,34969.164,55315.784,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2003,4.259,2.862,39261.866,58691.662,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,2004,5.411,4.025,44190.886,63438.701,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2005,4.836,3.556,47868.243,68527.144,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,2006,5.399,3.928,51832.937,74369.886,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2007,5.556,3.845,58516.949,80502.239,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2008,3.09,1.6,64226.136,84479.734,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,2009,-0.116,-2.043,60820.729,84661.834,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,2010,5.455,4.2,66542.408,90250.243,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2011,4.25,3.05,73828.892,95783.18,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,2012,3.518,2.48,75277.885,100861.421,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2013,3.407,2.59,77439.701,105797.541,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2014,3.527,2.837,79500.78,109738.13,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2015,3.427,2.833,75011.414,112006.525,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2016,3.237,2.611,76265.413,116311.044,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,2017,3.764,3.29,81088.946,122474.015,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2018,3.626,3.202,86095.664,129881.845,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2019,2.804,2.48,87325.54,135824.52,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2020,-2.803,-3.208,84960.903,133451.759,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2021,6.337,6.129,96487.666,148174.764,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2022,3.482,3.038,100135.361,163837.197,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2023,2.964,2.532,104476.432,174789.867,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2024,2.941,2.414,109734.27,183947.224,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2025,3.198,2.699,115598.839,193602.077,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2026,3.203,2.721,121580.994,203624.971,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2027,3.141,2.646,127499.667,213802.005,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df_tmp.isna().sum()

Subject Descriptor
Year                                                                                   0
Gross domestic product, constant prices                                                0
Gross domestic product, constant prices                                                0
Gross domestic product, current prices                                                 0
Gross domestic product, current prices                                                 0
Gross domestic product, deflator                                                      48
Gross domestic product per capita, constant prices                                    48
Gross domestic product per capita, current prices                                     48
Output gap                                                                            48
Gross domestic product based on purchasing-power-parity (PPP) share of world total    48
Investment                                                                             0
Gross national savings                                                                 0
Inflation, average consumer prices                                                     0
Inflation, end of period consumer prices                                               5
Trade volume of goods and services                                                     0
Volume of imports of goods and services                                                0
Volume of imports of goods                                                             0
Volume of exports of goods and services                                                0
Volume of exports of goods                                                             0
Terms of trade of goods and services                                                  48
Terms of trade of goods                                                               48
Export price of manufactures                                                          48
Export price of manufactures                                                          48
Unemployment rate                                                                     48
Employment                                                                            48
General government revenue                                                            48
General government total expenditure                                                  48
General government net lending/borrowing                                              48
General government structural balance                                                 48
General government primary net lending/borrowing                                      48
General government net debt                                                           48
General government gross debt                                                         48
Current account balance                                                                0
Current account balance                                                               48
Imports of goods and services                                                         48
Exports of goods and services                                                         48
Financial account balance                                                             48
Direct investment, net                                                                48
Portfolio investment, net                                                             48
Financial derivatives, net                                                            48
Other investment, net                                                                 48
Change in reserves                                                                    48
External debt, total                                                                  48
External debt, total                                                                  48
External debt, total                                                                  48
External debt, total debt service                                                     48
External debt, total debt service                                                     48
External debt, total debt service                                                     48
External debt, total debt service, interest                                           48
External debt, total debt service, interest                                           48
External debt, total debt service, interest                                           48
External debt, total debt service, amortization                                       48
External debt, total debt service, amortization                                       48
External debt, total debt service, amortization                                       48
dtype: int64

In [48]:
df_tmp.loc[:,df_tmp.isna().sum()<6]

Subject Descriptor,Year,"Gross domestic product, constant prices","Gross domestic product, constant prices","Gross domestic product, current prices","Gross domestic product, current prices",Investment,Gross national savings,"Inflation, average consumer prices","Inflation, end of period consumer prices",Trade volume of goods and services,Volume of imports of goods and services,Volume of imports of goods,Volume of exports of goods and services,Volume of exports of goods,Current account balance
0,Units,Percent change,Percent change (market exchange rates),U.S. dollars,Purchasing power parity; international dollars,Percent of GDP,Percent of GDP,Percent change,Percent change,Percent change,Percent change,Percent change,Percent change,Percent change,U.S. dollars
1,1980,2.151,1.697,11232.069,13401.939,26.5,23.722,17.356,NaN,3.112,1.528,1.206,4.706,4.583,-55.909
2,1981,2.052,2.073,11526.241,14988.046,25.896,23.398,15.105,NaN,3.447,2.266,1.114,4.601,4.807,-81.775
3,1982,0.694,0.486,11310.303,15971.455,24.436,22.091,14.311,NaN,-1.555,-1.635,-1.509,-1.478,-1.986,-91.53
4,1983,2.597,2.742,11610.283,16989.664,23.935,21.313,13.532,NaN,1.489,1.64,2.715,1.345,1.728,-75.695
5,1984,4.567,4.811,12025.117,18378.285,24.997,22.561,14.109,NaN,8.6,8.813,9.911,8.397,8.946,-67.706
6,1985,3.631,3.662,12553.732,19635.674,24.689,22.105,13.809,16.599,2.636,2.292,3.243,2.967,3.564,-63.327
7,1986,3.588,3.344,14793.158,20717.483,24.516,22.071,11.903,9.814,4.533,5.375,6.651,3.731,3.645,-66.065
8,1987,3.872,3.752,17032.786,22033.006,24.872,22.682,14.716,18.401,6.614,7.266,6.925,5.983,6.297,-63.218
9,1988,4.652,4.555,19156.083,23839.268,25.811,23.825,19.672,23.017,8.915,8.871,9.718,8.957,9.543,-56.852
10,1989,3.778,3.788,20154.504,25678.433,26.263,23.962,22.886,24.282,8.133,8.555,7.908,7.721,7.499,-82.928
11,1990,3.428,3.141,22643.041,27712.123,25.839,23.773,26.271,25.113,6.911,6.656,6.557,7.163,6.501,-111.122
12,1991,2.659,1.937,23667.7,29345.326,25.029,23.283,17.111,18.744,5.36,4.502,5.006,6.203,6.922,-151.394
13,1992,2.314,2.522,25351.636,33336.876,24.245,22.491,38.612,42.034,5.475,5.364,6.481,5.583,6.165,-135.698
14,1993,2.032,1.682,26075.732,34787.413,23.779,22.397,39.196,42.088,2.875,2.149,2.929,3.576,3.988,-66.567
15,1994,3.218,3.384,28026.544,36573.058,24.157,22.581,31.162,25.566,9.524,10.331,10.801,8.756,9.29,-88.543
16,1995,3.339,2.901,31243.753,38700.118,24.301,23.114,16.146,12.691,9.603,9.562,10.299,9.643,10.206,-74.027
17,1996,3.911,3.313,32113.067,40917.974,24.183,23.821,9.389,7.933,6.599,7.089,7.168,6.127,5.922,-62.027
18,1997,4.009,3.491,32029.533,43306.054,24.12,24.033,6.559,6.007,10.25,10.18,11.05,10.318,10.989,-8.692
19,1998,2.611,2.357,31881.27,45003.405,23.818,23.729,6.355,7.239,4.895,5.294,4.915,4.507,4.156,-82.308
20,1999,3.546,3.161,33008.737,47206.85,23.81,23.588,6.224,5.125,5.149,5.764,6.262,4.546,5.052,-98.944
21,2000,4.814,4.243,34103.065,50593.437,24.325,24.111,4.861,4.907,12.562,12.631,13.114,12.495,13.157,-156.376
22,2001,2.47,1.682,33857.249,52984.92,23.535,23.253,4.58,3.903,0.621,0.648,0.082,0.595,0.291,-187.75
23,2002,2.873,1.871,34969.164,55315.784,22.902,22.674,3.683,4.088,3.846,3.852,3.978,3.839,3.963,-145.964
24,2003,4.259,2.862,39261.866,58691.662,23.125,22.899,3.893,3.644,5.786,6.088,6.976,5.487,6.177,-84.609
25,2004,5.411,4.025,44190.886,63438.701,23.844,23.824,3.804,4.116,10.904,10.867,11.268,10.94,10.884,9.269
26,2005,4.836,3.556,47868.243,68527.144,24.215,24.322,4.032,3.973,7.915,8.08,8.389,7.75,7.842,49.514
27,2006,5.399,3.928,51832.937,74369.886,24.751,25.363,4.056,3.933,9.459,9.243,9.467,9.676,9.749,172.521
28,2007,5.556,3.845,58516.949,80502.239,25.275,25.506,4.293,5.3,8.034,8.277,8.017,7.793,7.222,206.169
29,2008,3.09,1.6,64226.136,84479.734,25.269,25.043,6.362,4.646,2.991,3.081,3.007,2.901,2.457,80.891
30,2009,-0.116,-2.043,60820.729,84661.834,23.242,23.205,2.72,3.079,-10.298,-10.732,-12.276,-9.863,-11.221,165.599
31,2010,5.455,4.2,66542.408,90250.243,24.447,24.78,3.694,4.272,12.815,12.605,13.914,13.024,14.682,292.231
32,2011,4.25,3.05,73828.892,95783.18,25.274,25.76,5.071,4.753,7.022,7.219,7.887,6.827,7.114,317.816
33,2012,3.518,2.48,75277.885,100861.421,25.42,26.149,4.081,3.951,3.133,2.963,2.581,3.301,3.328,372.916
34,2013,3.407,2.59,77439.701,105797.541,25.468,26.135,3.617,3.292,3.527,3.457,3.246,3.596,3.351,392.841
35,2014,3.527,2.837,79500.78,109738.13,25.756,26.576,3.228,2.905,3.838,4.073,3.113,3.605,2.919,370.634
36,2015,3.427,2.833,75011.414,112006.525,25.776,26.371,2.748,2.836,2.931,2.763,2.236,3.097,2.419,174.617
37,2016,3.237,2.611,76265.413,116311.044,25.447,25.964,2.744,3.019,2.242,2.175,2.137,2.308,2.021,250.594
38,2017,3.764,3.29,81088.946,122474.015,25.944,26.659,3.243,3.313,5.632,5.741,5.756,5.524,5.514,438.068
39,2018,3.626,3.202,86095.664,129881.845,26.49,26.999,3.617,3.561,4.032,4.3,4.284,3.766,3.34,319.621
40,2019,2.804,2.48,87325.54,135824.52,26.471,27.009,3.507,3.856,1.153,1.044,0.331,1.261,0.14,377.871
41,2020,-2.803,-3.208,84960.903,133451.759,26.359,27.003,3.247,2.907,-7.792,-8.106,-5.657,-7.481,-4.26,301.337
42,2021,6.337,6.129,96487.666,148174.764,27.071,28.083,4.697,6.343,10.874,10.848,11.588,10.9,10.839,866.444
43,2022,3.482,3.038,100135.361,163837.197,27.351,27.893,8.712,8.896,5.138,5.397,4.11,4.883,2.593,410.881
44,2023,2.964,2.532,104476.432,174789.867,26.361,26.332,6.876,6.35,0.869,0.651,-0.517,1.085,0.013,307.163
45,2024,2.941,2.414,109734.27,183947.224,26.189,26.228,5.794,5.088,3.518,3.527,3.121,3.509,3.211,363.974
46,2025,3.198,2.699,115598.839,193602.077,26.275,26.271,4.619,4.462,3.701,3.746,3.68,3.656,3.693,316.699
47,2026,3.203,2.721,121580.994,203624.971,26.431,26.375,4.226,4.029,3.581,3.654,3.65,3.51,3.514,252.748
48,2027,3.141,2.646,127499.667,213802.005,26.528,26.407,3.94,3.916,3.5,3.571,3.574,3.429,3.474,175.732

In [52]:
regions=['World']
subject='Current account balance'
units='U.S. dollars'
df_tmp=get_series(df_world,regions,subject,units,years)
df_tmp.tail()

    Year    World
43  2023  307.163
44  2024  363.974
45  2025  316.699
46  2026  252.748
47  2027  175.732

In [53]:
alt.Chart(df_tmp).mark_line(point=True).encode(
    alt.X('Year').title('Year'),
    alt.Y('World').title(subject+' ('+units+')'),
    tooltip=['Year', 'World']
).interactive()

alt.Chart(...)

In [54]:
regions=['World']
subject='Gross domestic product, constant prices'
units='Percent change'
df_tmp=get_series(df_world,regions,subject,units,years)
df_tmp.tail()

    Year  World
43  2023  2.964
44  2024  2.941
45  2025  3.198
46  2026  3.203
47  2027  3.141

In [55]:
alt.Chart(df_tmp).mark_line(point=True).encode(
    alt.X('Year').title('Year'),
    alt.Y('World').title(subject+' ('+units+')'),
    tooltip=['Year', 'World']
).interactive()

alt.Chart(...)

In [92]:
df_imf.head()

,Unnamed: 0,WEO Country Code,ISO,WEO Subject Code,Country,Subject Descriptor,Subject Notes,Units,Scale,Country/Series-specific Notes,...,2020,2021,2022,2023,2024,2025,2026,2027,2028,Estimates Start After
0,0,512,AFG,NGDP_R,Afghanistan,"Gross domestic product, constant prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,...,1288.87,1021.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
1,1,512,AFG,NGDP_RPCH,Afghanistan,"Gross domestic product, constant prices",Annual percentages of constant price GDP are y...,Percent change,NaN,"See notes for: Gross domestic product, consta...",...,-2.351,-20.737,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
2,2,512,AFG,NGDP,Afghanistan,"Gross domestic product, current prices",Expressed in billions of national currency uni...,National currency,Billions,Source: National Statistics Office Latest actu...,...,1547.29,1232.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
3,3,512,AFG,NGDPD,Afghanistan,"Gross domestic product, current prices",Values are based upon GDP in national currency...,U.S. dollars,Billions,"See notes for: Gross domestic product, curren...",...,20.136,14.941,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0
4,4,512,AFG,PPPGDP,Afghanistan,"Gross domestic product, current prices",These data form the basis for the country weig...,Purchasing power parity; international dollars,Billions,"See notes for: Gross domestic product, curren...",...,81.007,67.093,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.0

In [108]:
regions=['United States','China','India','France','Japan','Canada','Brasil','Germany','Mexico','United Kingdom']
subject='Gross domestic product, current prices'
units='U.S. dollars'
year=2023
years=np.arange(1980,2028).tolist()
# df_tmp=get_series(df_imf,regions,subject,units,years)
df_tmp=df_imf[(df_imf['Country'].isin(regions)) & (df_imf['Subject Descriptor']==subject) & (df_imf['Units']==units)]
cols_to_keep=['ISO',year]
df_tmp=df_tmp[cols_to_keep]
df_tmp=df_tmp.rename({year:str(year)},axis=1)
df_tmp.sort_values(by=str(year),ascending=False,inplace=True)
print(df_tmp.shape)
df_tmp

(10, 2)

      ISO      2023
8187  USA  26949.64
1587  CHN   17700.9
2819  DEU   4429.84
3743  JPN   4230.86
3391  IND   3732.22
8143  GBR   3332.06
2643  FRA   3049.02
1411  CAN   2117.81
4931  MEX   1811.47
4491  MAC     38.48

In [113]:
df_tmp['CumGDP']=df_tmp[str(year)].cumsum()
df_tmp

      ISO      2023    CumGDP
8187  USA  26949.64  26949.64
1587  CHN   17700.9  44650.54
2819  DEU   4429.84  49080.38
3743  JPN   4230.86  53311.24
3391  IND   3732.22  57043.46
8143  GBR   3332.06  60375.52
2643  FRA   3049.02  63424.54
1411  CAN   2117.81  65542.35
4931  MEX   1811.47  67353.82
4491  MAC     38.48   67392.3

In [104]:
base = alt.Chart(df_tmp).encode(
    alt.Theta("2023:Q").stack(True),
    alt.Color("ISO:N").legend(None)
).interactive()

pie = base.mark_arc(outerRadius=120)
text = base.mark_text(radius=140, size=20).encode(text="ISO:N")

pie + text

alt.LayerChart(...)